# Generated by Django 3.2 on 2022-05-26 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0002_rename_paintingmaterials_paintingmaterial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaintingDetail',
            fields=[
                ('painting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='paintings.painting')),
                ('details', models.TextField()),
            ],
        ),
    ]
