# Generated by Django 3.2 on 2022-05-26 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0003_paintingdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaintingDetail',
        ),
    ]
