version: "3"

services:
  pg:
    image: postgres
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: app
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    #volumes:
      #- pg-data:/var/lib/postgresql/data/

  plants:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      CONFIG_NAME: DevelopmentConfig
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://app:password@pg/plants
    ports:
      - "80:5000"
    volumes:
      - ./:/app
    depends_on:
      - pg

  plants-prod:
    build:
      context: .
      dockerfile: docker-build/Dockerfile
    environment:
      CONFIG_NAME: ProductionConfig
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://app:password@pg/plants
    ports:
      - "80:80"
    depends_on:
      - pg